# Generated by Django 2.1.2 on 2019-03-01 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Venter', '0015_auto_20190301_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='Venter.Profile'),
        ),
    ]
