# Generated by Django 2.1.2 on 2019-03-02 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Venter', '0016_auto_20190301_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name_plural': 'CSV File'},
        ),
    ]
