# Generated by Django 2.1.2 on 2019-03-01 10:13

import Venter.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venter', '0016_auto_20190301_0938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'permissions': (('delete_organisation_files', 'Can delete organisation files'),), 'verbose_name_plural': 'File'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='User Profile Picture/default-avatar.png', null=True, upload_to=Venter.helpers.get_user_profile_picture_path),
        ),
    ]
