# Generated by Django 2.1.2 on 2019-03-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venter', '0017_auto_20190302_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='output_file',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
