# Generated by Django 2.1.2 on 2019-03-01 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Venter', '0017_auto_20190301_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name_plural': 'File'},
        ),
        migrations.RenameField(
            model_name='file',
            old_name='csv_file',
            new_name='input_file',
        ),
    ]
