# Generated by Django 2.1.2 on 2019-03-05 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Venter', '0020_file_has_prediction'),
        ('Venter', '0018_file_output_file'),
    ]

    operations = [
    ]
