# Generated by Django 2.1.2 on 2019-03-05 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Venter', '0021_merge_20190305_1834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name_plural': 'File'},
        ),
        migrations.RenameField(
            model_name='file',
            old_name='output_file',
            new_name='output_file_json',
        ),
    ]
