# Generated by Django 2.1.2 on 2019-03-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venter', '0022_auto_20190305_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='output_file_xlsx',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
