# Generated by Django 2.1.2 on 2019-03-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venter', '0023_file_output_file_xlsx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='output_file_json',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='file',
            name='output_file_xlsx',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
