# Generated by Django 2.2 on 2019-04-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venter', '0027_auto_20190422_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_saved_status',
            field=models.BooleanField(default=False),
        ),
    ]
